[book]
authors = ["Niko Matsakis"]
language = "en"
multilingual = false
src = "src"
title = "Cross-Team Collaboration Fun Times"

[output.html]
site-url = "/ctcft/"
git-repository-url = "https://github.com/rust-lang/ctcft"

[output.html.fold]
enable = true
level = 0
